Remove package cleanup from GHA
kiegroup/optaweb-vehicle-routing pull request #474
Opened 2021-04-21 11:52 UTC by rsynek

According to the "df -h" output in the PR checks, the entire "Free disk space"
step frees up ~17 GB of disk space. Package cleanup, being part of it, frees ~4 GB,
but the enumeration of individual packages makes the CI brittle.

### JIRA

### Referenced pull requests

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

2021-04-21 14:34 UTC, rsynek commented
jenkins retest this

2021-04-22 07:07 UTC, rsynek commented
Ad Travis CI: "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself." - in the build history [1] I can see the last successful build was ~3 months ago. Does it work?

[1] https://travis-ci.com/github/kiegroup/optaweb-vehicle-routing/builds

2021-04-22 07:07 UTC, rsynek commented
jenkins retest this

2021-04-22 14:21 UTC, yurloc commented
@rsynek You can ignore Travis now. It was not working at all for a few months and I've forgotten about it. Theirs support have recently responded to my request and gave `kiegroup` some credits. As a result the builds unexpectedly started to run again and I'll evaluate how they work now.

2021-04-22 14:24 UTC, yurloc commented
@rsynek I mean, I'm probably going to remove Travis completely. I just want to do a few checks to see whether we lose anything if we do that.

2021-04-26 16:09 UTC, yurloc commented
@Ginxo you OK with this?

2021-04-27 07:41 UTC, Ginxo requested changes
please check @yurloc 
can you please change (github does not allow me to propose it) #9
from `os: [ubuntu-18.04, windows-latest]` to `os: [ubuntu-latest, windows-latest]`

2021-04-27 09:55 UTC, yurloc approved these changes

2021-04-27 09:56 UTC, merged