[BXMSPROD2057] Updating references to kie-ci repo.
kiegroup/optaweb-vehicle-routing pull request #867
Opened 2023-06-15 09:01 UTC by bacciotti

2023-06-15 09:02 UTC, lampajr approved these changes

2023-06-15 09:16 UTC, lampajr requested changes

2023-06-15 09:16 UTC, lampajr commented on .github/workflows/full-downstream.yml
>          with:
Just noticed, I think we miss `definition-file` here

2023-06-15 09:19 UTC, lampajr commented on .github/workflows/full-downstream.yml
>          with:
Added `run_fdb` label, it should fail with "missing definition file" or something similar

2023-06-16 06:50 UTC, lampajr approved these changes

2023-06-19 07:50 UTC, Ginxo approved these changes
LGTM

2023-06-19 07:51 UTC, merged